---
title: "Get started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Get started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Welcome!

Hello! We hope you are as excited as we are about the upcoming *intRo* workshop.

In order to get the most from the workshop, you will have to get yourself and your computer ready beforehand.

# Software requirements

You will need to **install R and RStudio** for the workshop.
Most beginners mix them up, but, to go with the popular car analogy, R is the car engine while RStudio is the car dashboard.

The statistical [programming language](https://www.codecademy.com/resources/blog/programming-languages/) **R** is the "engine" we will be using to do data visualisation and more.

**RStudio** is an integrated development environment (or [IDE](https://www.codecademy.com/articles/what-is-an-ide)), i.e. something that helps you take advantage of the powerful R programming language.
Think of RStudio as an interface to R (like the dashboard of a car is an interface to the engine).

# 1. Install R

Head over to the official R download page: <https://cloud.r-project.org>.

The first heading says `Download and Intall R`. Click on the download link (choose the one with your operating system: Linux, macOS or Windows). You will be redirected to the download page for your operating system.

If you have macOS, install the `Latest release` (`R-4.1.1-arm64` if you have a Mac with an M1 chip, `R-4.1.1` otherwise).

If you have Windows, from the download page click on `install R for the first time` and follow the instructions on the page.

Linux should come with R installed.

# 2. Install RStudio

You can download RStudio from the official page: <https://www.rstudio.com/products/rstudio/download/>.

Click on the `Download` button below `RStudio Desktop` and then download the recommended RStudio version for your operating system (no need to install R because you've already done that in the previous step).

# 3. Install the workshop materials

You can install the workshop materials by simply installing the intRo package.

To do so, open RStudio and paste the following lines of code into the Console (the bottom left panel).

```r
install.packages("remotes")
remotes::install_github("intro-rstats/intRo", build_vignettes = TRUE)
```

Then press enter/return to run the code.
All the necessary packages will be installed and the materials will be downloaded.
